name: CI/CD Pipeline

on: [push]
#  workflow_run:
#    workflows: ["E2E Workflow"]
#    types:
#      - completed

jobs:
  setup-java:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      java-version: '21'
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

  build-order-service:
    needs: setup-java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Services/Order Service
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Order Service JAR
        run: ./gradlew clean build

  build-delivery-service:
    needs: setup-java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Services/Delivery Service
    services: # <--- SERVICE CONTAINER VOOR MONGO
      mongo:
        image: mongo:latest # Of een specifieke versie zoals mongo:4.4, mongo:5.0
        ports:
          - 27017:27017 # Map de containerpoort naar de host (runner) poort
        env: # <--- MONGO INIT VARIABLES STAAN HIER
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }} # Gebruik correcte secret syntax
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} # Gebruik correcte secret syntax
          MONGO_INITDB_DATABASE: deliverydb # Optioneel: stel standaard DB in
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Delivery Service JAR
        env:
          OAUTH2_JWT_AUDIENCES: ${{ secrets.OAUTH2_JWT_AUDIENCES }}
          OAUTH2_JWT_ISSUER_URI: ${{ secrets.OAUTH2_JWT_ISSUER_URI }}
          MONGO_INITDB_URI:  ${{ secrets.MONGO_INITDB_URI }}
        run: ./gradlew clean build

  docker-login:
    runs-on: ubuntu-latest
    outputs:
      logged-in: ${{ steps.login.outcome }}
    steps:
    # In je push-delivery-service en push-order-service jobs, VOOR de docker build/push stap
    - name: Docker Logout (Force)
      run: docker logout docker.io || true # || true om te voorkomen dat de job faalt als er geen login was

    - name: Docker Login (Manual)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # of '494690'
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Zorg dat dit het juiste, werkende PAT is
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_step.outputs.new_docker_version }}
    steps:
      - name: Checkout code for versioning
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nodig om alle Git tags te kunnen fetchen

      - name: Calculate Next Docker Version
        id: version_step
        run: |
          set -e # Stop het script bij een fout
          
          # 1. Zorg dat je alle tags hebt van de remote
          git fetch --tags -f
          
          # 2. Vind de laatste semantische Git-tag (X.Y.Z formaat)
          LATEST_GIT_TAG=$(git tag --list '[0-9]*\.[0-9]*\.[0-9]*' --sort=-v:refname | head -n 1)
          
          # 3. Bepaal de nieuwe Docker versie
          if [ -z "$LATEST_GIT_TAG" ]; then
            NEW_DOCKER_VERSION="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_GIT_TAG"
            PATCH=$((PATCH + 1))
            NEW_DOCKER_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          
          echo "Laatste Git-tag (als basis voor Docker versie): $LATEST_GIT_TAG"
          echo "Nieuwe Docker versie wordt: $NEW_DOCKER_VERSION"
          
          # Stel de nieuwe versie in als output van deze stap
          echo "new_docker_version=$NEW_DOCKER_VERSION" >> $GITHUB_OUTPUT

  push-order-service:
    needs: [build-order-service, docker-login, calculate-version]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Services
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Order Service Image
        run: |
          VERSION=${{ needs.calculate-version.outputs.new_version }} # Gebruik berekende versie
          echo "Gebruik versie $VERSION voor order-service"
          docker build -t docker.io/494690/order-service:${VERSION} "Order Service"
          docker push docker.io/494690/order-service:${VERSION}

  push-delivery-service:
    needs: [build-delivery-service, docker-login, calculate-version]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Services
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Delivery Service Image
        run: |
          VERSION=${{ needs.calculate-version.outputs.new_version }} # Gebruik berekende versie
          echo "Gebruik versie $VERSION voor delivery-service"
          docker build -t docker.io/494690/test-image:${VERSION} "Delivery Service"
          docker push docker.io/494690/test-image:${VERSION}
