name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger pipeline on push to 'main' branch
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Order Service JAR
        working-directory: Backend/Services/order-service
        run: ./gradlew clean build

      - name: Build Delivery Service JAR
        working-directory: Backend/Services/delivery-service
        run: ./gradlew clean build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Order Service image
        working-directory: Backend/Services
        run: |
          docker build -t docker.io/494690/order-service:latest order-service
          docker push docker.io/494690/order-service:latest

      - name: Build and push Delivery Service image
        working-directory: Backend/Services
        run: |
          docker build -t docker.io/494690/delivery-service:latest delivery-service
          docker push docker.io/494690/delivery-service:latest